import { InventoryItem, Category, Unit } from './types';

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    id: 'SKU-001',
    name: 'Busi Champion',
    brand: 'Champion',
    category: 'Suku Cadang Mesin',
    unit: 'pcs',
    quantity: 15,
    min_stock: 10,
    max_stock: 50,
    last_updated: '2023-10-26T10:00:00Z',
    image: 'https://placehold.co/400x400.png',
  },
  {
    id: 'SKU-002',
    name: 'Oli Mesin Federal',
    brand: 'Federal Oil',
    category: 'Pelumas',
    unit: 'liter',
    quantity: 8,
    min_stock: 10,
    max_stock: 40,
    last_updated: '2023-10-25T14:30:00Z',
    image: 'https://placehold.co/400x400.png',
  },
  {
    id: 'SKU-003',
    name: 'Filter Udara Sakura',
    brand: 'Sakura',
    category: 'Filter',
    unit: 'pcs',
    quantity: 25,
    min_stock: 5,
    max_stock: 30,
    last_updated: '2023-10-26T11:00:00Z',
    image: 'https://placehold.co/400x400.png',
  },
  {
    id: 'SKU-004',
    name: 'Kampas Rem Bendix',
    brand: 'Bendix',
    category: 'Sistem Pengereman',
    unit: 'set',
    quantity: 4,
    min_stock: 5,
    max_stock: 20,
    last_updated: '2023-10-24T09:00:00Z',
    image: 'https://placehold.co/400x400.png',
  },
  {
    id: 'SKU-005',
    name: 'Aki GS Astra',
    brand: 'GS Astra',
    category: 'Kelistrikan',
    unit: 'pcs',
    quantity: 12,
    min_stock: 8,
    max_stock: 15,
    last_updated: '2023-10-26T08:15:00Z',
    image: 'https://placehold.co/400x400.png',
  },
  {
    id: 'SKU-006',
    name: 'Bohlam Philips',
    brand: 'Philips',
    category: 'Kelistrikan',
    unit: 'box',
    quantity: 50,
    min_stock: 20,
    max_stock: 100,
    last_updated: '2023-10-22T16:45:00Z',
    image: 'https://placehold.co/400x400.png',
  },
  {
    id: 'SKU-007',
    name: 'Bearing Roda NTN',
    brand: 'NTN',
    category: 'Suku Cadang Roda',
    unit: 'pcs',
    quantity: 30,
    min_stock: 15,
    max_stock: 50,
    last_updated: '2023-10-23T13:20:00Z',
    image: 'https://placehold.co/400x400.png',
  },
  {
    id: 'SKU-008',
    name: 'Van Belt Mitsuboshi',
    brand: 'Mitsuboshi',
    category: 'Suku Cadang Mesin',
    unit: 'pcs',
    quantity: 1,
    min_stock: 5,
    max_stock: 25,
    last_updated: '2023-10-26T15:00:00Z',
    image: 'https://placehold.co/400x400.png',
  },
];


export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-001', name: 'Suku Cadang Mesin' },
  { id: 'cat-002', name: 'Pelumas' },
  { id: 'cat-003', name: 'Filter' },
  { id: 'cat-004', name: 'Sistem Pengereman' },
  { id: 'cat-005', name: 'Kelistrikan' },
  { id: 'cat-006', name: 'Suku Cadang Roda' },
];

export const MOCK_UNITS: Unit[] = [
  { id: 'unit-001', name: 'pcs' },
  { id: 'unit-002', name: 'box' },
  { id: 'unit-003', name: 'liter' },
  { id: 'unit-004', name: 'kg' },
  { id: 'unit-005', name: 'set' },
];
